server:
  port: 8000

player:
  name: hieu
  age: 22
jwt:
  signerKey: oAHo1AG6CbA9K3i01Qqs5JEmTQKhqYUlV9y9G0QzhmgBYnmiArzN1fxJMkRU6D8n

#spring:
#  profiles:
#    active:

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ielts
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
cloudinary:
  name: hieu
  key: 719968447847423
  secret: 5g4vSxur9LbqXD7zT996W0Rgoco

Cloud name: dfx1uuk2x
#CLOUDINARY_URL=cloudinary://<your_api_key>:<your_api_secret>@dfx1uuk2x
